import api from '../../common/api'

export const GET_KINDERGARTEN_CLASS_SUCCESS = 'GET_KINDERGARTEN_CLASS_SUCCESS';
export const GET_KINDERGARTEN_CLASS_ERROR = 'GET_KINDERGARTEN_CLASS_ERROR';
export const RESET_KINDERGARTEN_CLASS = 'RESET_KINDERGARTEN_CLASS';
export const ADD_KINDERGARTEN_CLASS_SUCCESS = 'ADD_KINDERGARTEN_CLASS_SUCCESS';
export const ADD_KINDERGARTEN_CLASS_ERROR = 'ADD_KINDERGARTEN_CLASS_ERROR';
export const EDIT_KINDERGARTEN_CLASS_SUCCESS = 'EDIT_KINDERGARTEN_CLASS_SUCCESS';
export const EDIT_KINDERGARTEN_CLASS_ERROR = 'EDIT_KINDERGARTEN_CLASS_ERROR';
export const RESET_TRIGGER = 'RESET_TRIGGER';



export function resetKindergartenALL() {
    return {
        type: 'RESET_KINDERGARTEN_ALL'
    }
}

export function resetTrigger() {
    return {
        type: 'RESET_TRIGGER'
    }
}